Algoritmo "Atividade 3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz!
// Autor(a)    : Ângelo Gabriel Ribeiro Passos
// Data atual  : 22/03/2024
Var
   numero , A, B : inteiro


Inicio
      escreval("Digite um numero")
      leia(numero)

      se (numero > 0) entao
          A <- numero
          escreval("O numero", numero, " é positivo")
      senao
           B <- numero
           escreval("O numero",numero," ou é zero ou negativo")
      fimse

Fimalgoritmo