Algoritmo "Atividade do Angelo"

Var
dolar, dolar2 , reais, reais2, cotacao : real


Inicio
      cotacao <- 4.98
      dolar <- 1

      escreval("veja quanto esta o dolar")
      reais <- cotacao * dolar

      escreval(dolar, " dolar esta custando ",reais, " reais")

      escreval("quantos dolar irá investir hoje?")
      leia(dolar2)
      reais2 <- cotacao * dolar2


      escreval("você investiu", reais2, " reais ", " adquirindo ", dolar2, " dolares")


Fimalgoritmo